#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Base16 Shell
# Download scheme from https://github.com/chriskempson/base16-shell.
BASE16_SCHEME="tomorrow"
BASE16_SHELL="$HOME/.base16/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL


# Add composer folder to path.
if [[ -d "$HOME/.composer/vendor/bin" ]]; then
  export PATH="$HOME/.composer/vendor/bin:$PATH"
fi
